name = "vitessedge"
type = "webpack"
account_id = "f2f4cc760b9f87feb141a07838e85f5d"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

[site]
bucket = "../dist/client"
entry-point = "."
